############################
#Swift Economy by tatemylov#
############################

############################
#MySQL Configuration (Required)
MySQL:
  Username: Username
  Password: Password
  Ip: 0.0.0.0
  Database: Database
############################

############################
#General Tweaks

#Change the symbol of the currency
currency: "$"

#How much money to give the player when they join first time
starting-amount: 0